/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OsirisRouteImport } from './routes/osiris'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AnalisaAiRouteImport } from './routes/analisa-ai'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalisaAiHistoryRouteImport } from './routes/analisa-ai.history'
import { Route as ApiPublicWaIncomingRouteImport } from './routes/api/public/wa/incoming'
import { Route as ApiPublicTgIncomingRouteImport } from './routes/api/public/tg/incoming'
import { Route as ApiPublicHooksAnalisaTickRouteImport } from './routes/api/public/hooks/analisa-tick'

const OsirisRoute = OsirisRouteImport.update({
  id: '/osiris',
  path: '/osiris',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalisaAiRoute = AnalisaAiRouteImport.update({
  id: '/analisa-ai',
  path: '/analisa-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalisaAiHistoryRoute = AnalisaAiHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AnalisaAiRoute,
} as any)
const ApiPublicWaIncomingRoute = ApiPublicWaIncomingRouteImport.update({
  id: '/api/public/wa/incoming',
  path: '/api/public/wa/incoming',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTgIncomingRoute = ApiPublicTgIncomingRouteImport.update({
  id: '/api/public/tg/incoming',
  path: '/api/public/tg/incoming',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksAnalisaTickRoute =
  ApiPublicHooksAnalisaTickRouteImport.update({
    id: '/api/public/hooks/analisa-tick',
    path: '/api/public/hooks/analisa-tick',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analisa-ai': typeof AnalisaAiRouteWithChildren
  '/login': typeof LoginRoute
  '/osiris': typeof OsirisRoute
  '/analisa-ai/history': typeof AnalisaAiHistoryRoute
  '/api/public/hooks/analisa-tick': typeof ApiPublicHooksAnalisaTickRoute
  '/api/public/tg/incoming': typeof ApiPublicTgIncomingRoute
  '/api/public/wa/incoming': typeof ApiPublicWaIncomingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analisa-ai': typeof AnalisaAiRouteWithChildren
  '/login': typeof LoginRoute
  '/osiris': typeof OsirisRoute
  '/analisa-ai/history': typeof AnalisaAiHistoryRoute
  '/api/public/hooks/analisa-tick': typeof ApiPublicHooksAnalisaTickRoute
  '/api/public/tg/incoming': typeof ApiPublicTgIncomingRoute
  '/api/public/wa/incoming': typeof ApiPublicWaIncomingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analisa-ai': typeof AnalisaAiRouteWithChildren
  '/login': typeof LoginRoute
  '/osiris': typeof OsirisRoute
  '/analisa-ai/history': typeof AnalisaAiHistoryRoute
  '/api/public/hooks/analisa-tick': typeof ApiPublicHooksAnalisaTickRoute
  '/api/public/tg/incoming': typeof ApiPublicTgIncomingRoute
  '/api/public/wa/incoming': typeof ApiPublicWaIncomingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analisa-ai'
    | '/login'
    | '/osiris'
    | '/analisa-ai/history'
    | '/api/public/hooks/analisa-tick'
    | '/api/public/tg/incoming'
    | '/api/public/wa/incoming'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analisa-ai'
    | '/login'
    | '/osiris'
    | '/analisa-ai/history'
    | '/api/public/hooks/analisa-tick'
    | '/api/public/tg/incoming'
    | '/api/public/wa/incoming'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analisa-ai'
    | '/login'
    | '/osiris'
    | '/analisa-ai/history'
    | '/api/public/hooks/analisa-tick'
    | '/api/public/tg/incoming'
    | '/api/public/wa/incoming'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnalisaAiRoute: typeof AnalisaAiRouteWithChildren
  LoginRoute: typeof LoginRoute
  OsirisRoute: typeof OsirisRoute
  ApiPublicHooksAnalisaTickRoute: typeof ApiPublicHooksAnalisaTickRoute
  ApiPublicTgIncomingRoute: typeof ApiPublicTgIncomingRoute
  ApiPublicWaIncomingRoute: typeof ApiPublicWaIncomingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/osiris': {
      id: '/osiris'
      path: '/osiris'
      fullPath: '/osiris'
      preLoaderRoute: typeof OsirisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analisa-ai': {
      id: '/analisa-ai'
      path: '/analisa-ai'
      fullPath: '/analisa-ai'
      preLoaderRoute: typeof AnalisaAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analisa-ai/history': {
      id: '/analisa-ai/history'
      path: '/history'
      fullPath: '/analisa-ai/history'
      preLoaderRoute: typeof AnalisaAiHistoryRouteImport
      parentRoute: typeof AnalisaAiRoute
    }
    '/api/public/wa/incoming': {
      id: '/api/public/wa/incoming'
      path: '/api/public/wa/incoming'
      fullPath: '/api/public/wa/incoming'
      preLoaderRoute: typeof ApiPublicWaIncomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tg/incoming': {
      id: '/api/public/tg/incoming'
      path: '/api/public/tg/incoming'
      fullPath: '/api/public/tg/incoming'
      preLoaderRoute: typeof ApiPublicTgIncomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/analisa-tick': {
      id: '/api/public/hooks/analisa-tick'
      path: '/api/public/hooks/analisa-tick'
      fullPath: '/api/public/hooks/analisa-tick'
      preLoaderRoute: typeof ApiPublicHooksAnalisaTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AnalisaAiRouteChildren {
  AnalisaAiHistoryRoute: typeof AnalisaAiHistoryRoute
}

const AnalisaAiRouteChildren: AnalisaAiRouteChildren = {
  AnalisaAiHistoryRoute: AnalisaAiHistoryRoute,
}

const AnalisaAiRouteWithChildren = AnalisaAiRoute._addFileChildren(
  AnalisaAiRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnalisaAiRoute: AnalisaAiRouteWithChildren,
  LoginRoute: LoginRoute,
  OsirisRoute: OsirisRoute,
  ApiPublicHooksAnalisaTickRoute: ApiPublicHooksAnalisaTickRoute,
  ApiPublicTgIncomingRoute: ApiPublicTgIncomingRoute,
  ApiPublicWaIncomingRoute: ApiPublicWaIncomingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
